name: Firebase Web CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  Build_Deploy_Web:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    env:
      CI_FIREBASE_MESSAGE: ${{ github.event.head_commit.message }} - ${{ github.event.head_commit.url }}/checks

    steps:
      ## Checkout current branch
      - uses: actions/checkout@v1

      ## Setup node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      ## Install dependencies
      - name: npm install
        run: |
          npm i

      ## Build & Deploy Staging
      - name: Build & Deploy Staging
        if: contains(github.ref, 'refs/heads/release/')
        run: |
          npm run build
          npm firebase deploy --only hosting -P staging --token ${{ SECRETS.CI_FIREBASE_TOKEN }} --message "$CI_FIREBASE_MESSAGE"

      ## Build & Deploy Production
      - name: Build & Deploy Production
        if: github.ref == 'refs/heads/master'
        run: |
          npm run build
          npm firebase deploy --only hosting -P production --token ${{ SECRETS.CI_FIREBASE_TOKEN }} --message "$CI_FIREBASE_MESSAGE"