name: Firebase Web CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  Build_Deploy_Web:
    runs-on: ubuntu-latest
    env:
      CI_FIREBASE_MESSAGE: ${{ github.event.head_commit.message }} - ${{ github.event.head_commit.url }}/checks

    steps:
      ## Install dependencies
      - name: npm install
        run: |
          npm i

      ## Build & Deploy Staging
      name : Build & Deploy Staging
      if: contains(github.ref, 'refs/heads/develop/')
        run: |
        npm run build
        firebase deploy --only hosting -P staging --token ${{ SECRETS.CI_FIREBASE_TOKEN }} --message "$CI_FIREBASE_MESSAGE"

      ## Build & Deploy Production
      name : Build & Deploy Production
      if: github.ref == 'refs/heads/master'
        run: |
        npm run build
        firebase deploy --only hosting -P default --token ${{ SECRETS.CI_FIREBASE_TOKEN }} --message "$CI_FIREBASE_MESSAGE"
          
