name: Firebase Web CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  Build_Deploy_Web:
    runs-on: ubuntu-latest

    env:
      CI_FIREBASE_MESSAGE: ${{ github.event.head_commit.message }} - ${{ github.event.head_commit.url }}/checks

    steps:
      ## Checkout current branch
      - uses: actions/checkout@v1

      ## Install dependencies
      - name: npm install
        run: |
          npm i

      ## Build & Deploy Staging
      - name: Build Staging
        run : npm run build
      - name : Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting -P staging --message "$CI_FIREBASE_MESSAGE"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      ## Build & Deploy Production
      - name: Build Production
        run: npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting -P default --message "$CI_FIREBASE_MESSAGE"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          